// Liste complète des pays et indicatifs internationaux.
// Générée à partir de libphonenumber-js (source de référence) et Intl.DisplayNames.
export type PhoneCountry = {
  code: string;
  dial: string;
  fr: string;
  en: string;
  flag: string;
};

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: "AF", dial: "+93", fr: "Afghanistan", en: "Afghanistan", flag: "🇦🇫" },
  { code: "ZA", dial: "+27", fr: "Afrique du Sud", en: "South Africa", flag: "🇿🇦" },
  { code: "AL", dial: "+355", fr: "Albanie", en: "Albania", flag: "🇦🇱" },
  { code: "DZ", dial: "+213", fr: "Algérie", en: "Algeria", flag: "🇩🇿" },
  { code: "DE", dial: "+49", fr: "Allemagne", en: "Germany", flag: "🇩🇪" },
  { code: "AD", dial: "+376", fr: "Andorre", en: "Andorra", flag: "🇦🇩" },
  { code: "AO", dial: "+244", fr: "Angola", en: "Angola", flag: "🇦🇴" },
  { code: "AI", dial: "+1", fr: "Anguilla", en: "Anguilla", flag: "🇦🇮" },
  { code: "AG", dial: "+1", fr: "Antigua-et-Barbuda", en: "Antigua & Barbuda", flag: "🇦🇬" },
  { code: "SA", dial: "+966", fr: "Arabie saoudite", en: "Saudi Arabia", flag: "🇸🇦" },
  { code: "AR", dial: "+54", fr: "Argentine", en: "Argentina", flag: "🇦🇷" },
  { code: "AM", dial: "+374", fr: "Arménie", en: "Armenia", flag: "🇦🇲" },
  { code: "AW", dial: "+297", fr: "Aruba", en: "Aruba", flag: "🇦🇼" },
  { code: "AU", dial: "+61", fr: "Australie", en: "Australia", flag: "🇦🇺" },
  { code: "AT", dial: "+43", fr: "Autriche", en: "Austria", flag: "🇦🇹" },
  { code: "AZ", dial: "+994", fr: "Azerbaïdjan", en: "Azerbaijan", flag: "🇦🇿" },
  { code: "BS", dial: "+1", fr: "Bahamas", en: "Bahamas", flag: "🇧🇸" },
  { code: "BH", dial: "+973", fr: "Bahreïn", en: "Bahrain", flag: "🇧🇭" },
  { code: "BD", dial: "+880", fr: "Bangladesh", en: "Bangladesh", flag: "🇧🇩" },
  { code: "BB", dial: "+1", fr: "Barbade", en: "Barbados", flag: "🇧🇧" },
  { code: "BE", dial: "+32", fr: "Belgique", en: "Belgium", flag: "🇧🇪" },
  { code: "BZ", dial: "+501", fr: "Belize", en: "Belize", flag: "🇧🇿" },
  { code: "BJ", dial: "+229", fr: "Bénin", en: "Benin", flag: "🇧🇯" },
  { code: "BM", dial: "+1", fr: "Bermudes", en: "Bermuda", flag: "🇧🇲" },
  { code: "BT", dial: "+975", fr: "Bhoutan", en: "Bhutan", flag: "🇧🇹" },
  { code: "BY", dial: "+375", fr: "Biélorussie", en: "Belarus", flag: "🇧🇾" },
  { code: "BO", dial: "+591", fr: "Bolivie", en: "Bolivia", flag: "🇧🇴" },
  { code: "BA", dial: "+387", fr: "Bosnie-Herzégovine", en: "Bosnia & Herzegovina", flag: "🇧🇦" },
  { code: "BW", dial: "+267", fr: "Botswana", en: "Botswana", flag: "🇧🇼" },
  { code: "BR", dial: "+55", fr: "Brésil", en: "Brazil", flag: "🇧🇷" },
  { code: "BN", dial: "+673", fr: "Brunei", en: "Brunei", flag: "🇧🇳" },
  { code: "BG", dial: "+359", fr: "Bulgarie", en: "Bulgaria", flag: "🇧🇬" },
  { code: "BF", dial: "+226", fr: "Burkina Faso", en: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", dial: "+257", fr: "Burundi", en: "Burundi", flag: "🇧🇮" },
  { code: "KH", dial: "+855", fr: "Cambodge", en: "Cambodia", flag: "🇰🇭" },
  { code: "CM", dial: "+237", fr: "Cameroun", en: "Cameroon", flag: "🇨🇲" },
  { code: "CA", dial: "+1", fr: "Canada", en: "Canada", flag: "🇨🇦" },
  { code: "CV", dial: "+238", fr: "Cap-Vert", en: "Cape Verde", flag: "🇨🇻" },
  { code: "CL", dial: "+56", fr: "Chili", en: "Chile", flag: "🇨🇱" },
  { code: "CN", dial: "+86", fr: "Chine", en: "China", flag: "🇨🇳" },
  { code: "CY", dial: "+357", fr: "Chypre", en: "Cyprus", flag: "🇨🇾" },
  { code: "CO", dial: "+57", fr: "Colombie", en: "Colombia", flag: "🇨🇴" },
  { code: "KM", dial: "+269", fr: "Comores", en: "Comoros", flag: "🇰🇲" },
  { code: "CG", dial: "+242", fr: "Congo-Brazzaville", en: "Congo - Brazzaville", flag: "🇨🇬" },
  { code: "CD", dial: "+243", fr: "Congo-Kinshasa", en: "Congo - Kinshasa", flag: "🇨🇩" },
  { code: "KP", dial: "+850", fr: "Corée du Nord", en: "North Korea", flag: "🇰🇵" },
  { code: "KR", dial: "+82", fr: "Corée du Sud", en: "South Korea", flag: "🇰🇷" },
  { code: "CR", dial: "+506", fr: "Costa Rica", en: "Costa Rica", flag: "🇨🇷" },
  { code: "CI", dial: "+225", fr: "Côte d’Ivoire", en: "Côte d’Ivoire", flag: "🇨🇮" },
  { code: "HR", dial: "+385", fr: "Croatie", en: "Croatia", flag: "🇭🇷" },
  { code: "CU", dial: "+53", fr: "Cuba", en: "Cuba", flag: "🇨🇺" },
  { code: "CW", dial: "+599", fr: "Curaçao", en: "Curaçao", flag: "🇨🇼" },
  { code: "DK", dial: "+45", fr: "Danemark", en: "Denmark", flag: "🇩🇰" },
  { code: "DJ", dial: "+253", fr: "Djibouti", en: "Djibouti", flag: "🇩🇯" },
  { code: "DM", dial: "+1", fr: "Dominique", en: "Dominica", flag: "🇩🇲" },
  { code: "EG", dial: "+20", fr: "Égypte", en: "Egypt", flag: "🇪🇬" },
  { code: "AE", dial: "+971", fr: "Émirats arabes unis", en: "United Arab Emirates", flag: "🇦🇪" },
  { code: "EC", dial: "+593", fr: "Équateur", en: "Ecuador", flag: "🇪🇨" },
  { code: "ER", dial: "+291", fr: "Érythrée", en: "Eritrea", flag: "🇪🇷" },
  { code: "ES", dial: "+34", fr: "Espagne", en: "Spain", flag: "🇪🇸" },
  { code: "EE", dial: "+372", fr: "Estonie", en: "Estonia", flag: "🇪🇪" },
  { code: "SZ", dial: "+268", fr: "Eswatini", en: "Eswatini", flag: "🇸🇿" },
  { code: "VA", dial: "+39", fr: "État de la Cité du Vatican", en: "Vatican City", flag: "🇻🇦" },
  { code: "US", dial: "+1", fr: "États-Unis", en: "United States", flag: "🇺🇸" },
  { code: "ET", dial: "+251", fr: "Éthiopie", en: "Ethiopia", flag: "🇪🇹" },
  { code: "FJ", dial: "+679", fr: "Fidji", en: "Fiji", flag: "🇫🇯" },
  { code: "FI", dial: "+358", fr: "Finlande", en: "Finland", flag: "🇫🇮" },
  { code: "FR", dial: "+33", fr: "France", en: "France", flag: "🇫🇷" },
  { code: "GA", dial: "+241", fr: "Gabon", en: "Gabon", flag: "🇬🇦" },
  { code: "GM", dial: "+220", fr: "Gambie", en: "Gambia", flag: "🇬🇲" },
  { code: "GE", dial: "+995", fr: "Géorgie", en: "Georgia", flag: "🇬🇪" },
  { code: "GH", dial: "+233", fr: "Ghana", en: "Ghana", flag: "🇬🇭" },
  { code: "GI", dial: "+350", fr: "Gibraltar", en: "Gibraltar", flag: "🇬🇮" },
  { code: "GR", dial: "+30", fr: "Grèce", en: "Greece", flag: "🇬🇷" },
  { code: "GD", dial: "+1", fr: "Grenade", en: "Grenada", flag: "🇬🇩" },
  { code: "GL", dial: "+299", fr: "Groenland", en: "Greenland", flag: "🇬🇱" },
  { code: "GP", dial: "+590", fr: "Guadeloupe", en: "Guadeloupe", flag: "🇬🇵" },
  { code: "GU", dial: "+1", fr: "Guam", en: "Guam", flag: "🇬🇺" },
  { code: "GT", dial: "+502", fr: "Guatemala", en: "Guatemala", flag: "🇬🇹" },
  { code: "GG", dial: "+44", fr: "Guernesey", en: "Guernsey", flag: "🇬🇬" },
  { code: "GN", dial: "+224", fr: "Guinée", en: "Guinea", flag: "🇬🇳" },
  { code: "GQ", dial: "+240", fr: "Guinée équatoriale", en: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "GW", dial: "+245", fr: "Guinée-Bissau", en: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "GY", dial: "+592", fr: "Guyana", en: "Guyana", flag: "🇬🇾" },
  { code: "GF", dial: "+594", fr: "Guyane française", en: "French Guiana", flag: "🇬🇫" },
  { code: "HT", dial: "+509", fr: "Haïti", en: "Haiti", flag: "🇭🇹" },
  { code: "HN", dial: "+504", fr: "Honduras", en: "Honduras", flag: "🇭🇳" },
  { code: "HU", dial: "+36", fr: "Hongrie", en: "Hungary", flag: "🇭🇺" },
  { code: "CX", dial: "+61", fr: "Île Christmas", en: "Christmas Island", flag: "🇨🇽" },
  { code: "AC", dial: "+247", fr: "Île de l’Ascension", en: "Ascension Island", flag: "🇦🇨" },
  { code: "IM", dial: "+44", fr: "Île de Man", en: "Isle of Man", flag: "🇮🇲" },
  { code: "NF", dial: "+672", fr: "Île Norfolk", en: "Norfolk Island", flag: "🇳🇫" },
  { code: "AX", dial: "+358", fr: "Îles Åland", en: "Åland Islands", flag: "🇦🇽" },
  { code: "KY", dial: "+1", fr: "Îles Caïmans", en: "Cayman Islands", flag: "🇰🇾" },
  { code: "CC", dial: "+61", fr: "Îles Cocos", en: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  { code: "CK", dial: "+682", fr: "Îles Cook", en: "Cook Islands", flag: "🇨🇰" },
  { code: "FO", dial: "+298", fr: "Îles Féroé", en: "Faroe Islands", flag: "🇫🇴" },
  { code: "FK", dial: "+500", fr: "Îles Malouines", en: "Falkland Islands", flag: "🇫🇰" },
  { code: "MP", dial: "+1", fr: "Îles Mariannes du Nord", en: "Northern Mariana Islands", flag: "🇲🇵" },
  { code: "MH", dial: "+692", fr: "Îles Marshall", en: "Marshall Islands", flag: "🇲🇭" },
  { code: "SB", dial: "+677", fr: "Îles Salomon", en: "Solomon Islands", flag: "🇸🇧" },
  { code: "TC", dial: "+1", fr: "Îles Turques-et-Caïques", en: "Turks & Caicos Islands", flag: "🇹🇨" },
  { code: "VG", dial: "+1", fr: "Îles Vierges britanniques", en: "British Virgin Islands", flag: "🇻🇬" },
  { code: "VI", dial: "+1", fr: "Îles Vierges des États-Unis", en: "U.S. Virgin Islands", flag: "🇻🇮" },
  { code: "IN", dial: "+91", fr: "Inde", en: "India", flag: "🇮🇳" },
  { code: "ID", dial: "+62", fr: "Indonésie", en: "Indonesia", flag: "🇮🇩" },
  { code: "IQ", dial: "+964", fr: "Irak", en: "Iraq", flag: "🇮🇶" },
  { code: "IR", dial: "+98", fr: "Iran", en: "Iran", flag: "🇮🇷" },
  { code: "IE", dial: "+353", fr: "Irlande", en: "Ireland", flag: "🇮🇪" },
  { code: "IS", dial: "+354", fr: "Islande", en: "Iceland", flag: "🇮🇸" },
  { code: "IL", dial: "+972", fr: "Israël", en: "Israel", flag: "🇮🇱" },
  { code: "IT", dial: "+39", fr: "Italie", en: "Italy", flag: "🇮🇹" },
  { code: "JM", dial: "+1", fr: "Jamaïque", en: "Jamaica", flag: "🇯🇲" },
  { code: "JP", dial: "+81", fr: "Japon", en: "Japan", flag: "🇯🇵" },
  { code: "JE", dial: "+44", fr: "Jersey", en: "Jersey", flag: "🇯🇪" },
  { code: "JO", dial: "+962", fr: "Jordanie", en: "Jordan", flag: "🇯🇴" },
  { code: "KZ", dial: "+7", fr: "Kazakhstan", en: "Kazakhstan", flag: "🇰🇿" },
  { code: "KE", dial: "+254", fr: "Kenya", en: "Kenya", flag: "🇰🇪" },
  { code: "KG", dial: "+996", fr: "Kirghizstan", en: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "KI", dial: "+686", fr: "Kiribati", en: "Kiribati", flag: "🇰🇮" },
  { code: "XK", dial: "+383", fr: "Kosovo", en: "Kosovo", flag: "🇽🇰" },
  { code: "KW", dial: "+965", fr: "Koweït", en: "Kuwait", flag: "🇰🇼" },
  { code: "RE", dial: "+262", fr: "La Réunion", en: "Réunion", flag: "🇷🇪" },
  { code: "LA", dial: "+856", fr: "Laos", en: "Laos", flag: "🇱🇦" },
  { code: "LS", dial: "+266", fr: "Lesotho", en: "Lesotho", flag: "🇱🇸" },
  { code: "LV", dial: "+371", fr: "Lettonie", en: "Latvia", flag: "🇱🇻" },
  { code: "LB", dial: "+961", fr: "Liban", en: "Lebanon", flag: "🇱🇧" },
  { code: "LR", dial: "+231", fr: "Liberia", en: "Liberia", flag: "🇱🇷" },
  { code: "LY", dial: "+218", fr: "Libye", en: "Libya", flag: "🇱🇾" },
  { code: "LI", dial: "+423", fr: "Liechtenstein", en: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", dial: "+370", fr: "Lituanie", en: "Lithuania", flag: "🇱🇹" },
  { code: "LU", dial: "+352", fr: "Luxembourg", en: "Luxembourg", flag: "🇱🇺" },
  { code: "MK", dial: "+389", fr: "Macédoine du Nord", en: "North Macedonia", flag: "🇲🇰" },
  { code: "MG", dial: "+261", fr: "Madagascar", en: "Madagascar", flag: "🇲🇬" },
  { code: "MY", dial: "+60", fr: "Malaisie", en: "Malaysia", flag: "🇲🇾" },
  { code: "MW", dial: "+265", fr: "Malawi", en: "Malawi", flag: "🇲🇼" },
  { code: "MV", dial: "+960", fr: "Maldives", en: "Maldives", flag: "🇲🇻" },
  { code: "ML", dial: "+223", fr: "Mali", en: "Mali", flag: "🇲🇱" },
  { code: "MT", dial: "+356", fr: "Malte", en: "Malta", flag: "🇲🇹" },
  { code: "MA", dial: "+212", fr: "Maroc", en: "Morocco", flag: "🇲🇦" },
  { code: "MQ", dial: "+596", fr: "Martinique", en: "Martinique", flag: "🇲🇶" },
  { code: "MU", dial: "+230", fr: "Maurice", en: "Mauritius", flag: "🇲🇺" },
  { code: "MR", dial: "+222", fr: "Mauritanie", en: "Mauritania", flag: "🇲🇷" },
  { code: "YT", dial: "+262", fr: "Mayotte", en: "Mayotte", flag: "🇾🇹" },
  { code: "MX", dial: "+52", fr: "Mexique", en: "Mexico", flag: "🇲🇽" },
  { code: "FM", dial: "+691", fr: "Micronésie", en: "Micronesia", flag: "🇫🇲" },
  { code: "MD", dial: "+373", fr: "Moldavie", en: "Moldova", flag: "🇲🇩" },
  { code: "MC", dial: "+377", fr: "Monaco", en: "Monaco", flag: "🇲🇨" },
  { code: "MN", dial: "+976", fr: "Mongolie", en: "Mongolia", flag: "🇲🇳" },
  { code: "ME", dial: "+382", fr: "Monténégro", en: "Montenegro", flag: "🇲🇪" },
  { code: "MS", dial: "+1", fr: "Montserrat", en: "Montserrat", flag: "🇲🇸" },
  { code: "MZ", dial: "+258", fr: "Mozambique", en: "Mozambique", flag: "🇲🇿" },
  { code: "MM", dial: "+95", fr: "Myanmar (Birmanie)", en: "Myanmar (Burma)", flag: "🇲🇲" },
  { code: "NA", dial: "+264", fr: "Namibie", en: "Namibia", flag: "🇳🇦" },
  { code: "NR", dial: "+674", fr: "Nauru", en: "Nauru", flag: "🇳🇷" },
  { code: "NP", dial: "+977", fr: "Népal", en: "Nepal", flag: "🇳🇵" },
  { code: "NI", dial: "+505", fr: "Nicaragua", en: "Nicaragua", flag: "🇳🇮" },
  { code: "NE", dial: "+227", fr: "Niger", en: "Niger", flag: "🇳🇪" },
  { code: "NG", dial: "+234", fr: "Nigeria", en: "Nigeria", flag: "🇳🇬" },
  { code: "NU", dial: "+683", fr: "Niue", en: "Niue", flag: "🇳🇺" },
  { code: "NO", dial: "+47", fr: "Norvège", en: "Norway", flag: "🇳🇴" },
  { code: "NC", dial: "+687", fr: "Nouvelle-Calédonie", en: "New Caledonia", flag: "🇳🇨" },
  { code: "NZ", dial: "+64", fr: "Nouvelle-Zélande", en: "New Zealand", flag: "🇳🇿" },
  { code: "OM", dial: "+968", fr: "Oman", en: "Oman", flag: "🇴🇲" },
  { code: "UG", dial: "+256", fr: "Ouganda", en: "Uganda", flag: "🇺🇬" },
  { code: "UZ", dial: "+998", fr: "Ouzbékistan", en: "Uzbekistan", flag: "🇺🇿" },
  { code: "PK", dial: "+92", fr: "Pakistan", en: "Pakistan", flag: "🇵🇰" },
  { code: "PW", dial: "+680", fr: "Palaos", en: "Palau", flag: "🇵🇼" },
  { code: "PA", dial: "+507", fr: "Panama", en: "Panama", flag: "🇵🇦" },
  { code: "PG", dial: "+675", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea", flag: "🇵🇬" },
  { code: "PY", dial: "+595", fr: "Paraguay", en: "Paraguay", flag: "🇵🇾" },
  { code: "NL", dial: "+31", fr: "Pays-Bas", en: "Netherlands", flag: "🇳🇱" },
  { code: "BQ", dial: "+599", fr: "Pays-Bas caribéens", en: "Caribbean Netherlands", flag: "🇧🇶" },
  { code: "PE", dial: "+51", fr: "Pérou", en: "Peru", flag: "🇵🇪" },
  { code: "PH", dial: "+63", fr: "Philippines", en: "Philippines", flag: "🇵🇭" },
  { code: "PL", dial: "+48", fr: "Pologne", en: "Poland", flag: "🇵🇱" },
  { code: "PF", dial: "+689", fr: "Polynésie française", en: "French Polynesia", flag: "🇵🇫" },
  { code: "PR", dial: "+1", fr: "Porto Rico", en: "Puerto Rico", flag: "🇵🇷" },
  { code: "PT", dial: "+351", fr: "Portugal", en: "Portugal", flag: "🇵🇹" },
  { code: "QA", dial: "+974", fr: "Qatar", en: "Qatar", flag: "🇶🇦" },
  { code: "HK", dial: "+852", fr: "R.A.S. chinoise de Hong Kong", en: "Hong Kong SAR China", flag: "🇭🇰" },
  { code: "MO", dial: "+853", fr: "R.A.S. chinoise de Macao", en: "Macao SAR China", flag: "🇲🇴" },
  { code: "CF", dial: "+236", fr: "République centrafricaine", en: "Central African Republic", flag: "🇨🇫" },
  { code: "DO", dial: "+1", fr: "République dominicaine", en: "Dominican Republic", flag: "🇩🇴" },
  { code: "RO", dial: "+40", fr: "Roumanie", en: "Romania", flag: "🇷🇴" },
  { code: "GB", dial: "+44", fr: "Royaume-Uni", en: "United Kingdom", flag: "🇬🇧" },
  { code: "RU", dial: "+7", fr: "Russie", en: "Russia", flag: "🇷🇺" },
  { code: "RW", dial: "+250", fr: "Rwanda", en: "Rwanda", flag: "🇷🇼" },
  { code: "EH", dial: "+212", fr: "Sahara occidental", en: "Western Sahara", flag: "🇪🇭" },
  { code: "BL", dial: "+590", fr: "Saint-Barthélemy", en: "St. Barthélemy", flag: "🇧🇱" },
  { code: "KN", dial: "+1", fr: "Saint-Christophe-et-Niévès", en: "St. Kitts & Nevis", flag: "🇰🇳" },
  { code: "SM", dial: "+378", fr: "Saint-Marin", en: "San Marino", flag: "🇸🇲" },
  { code: "MF", dial: "+590", fr: "Saint-Martin", en: "St. Martin", flag: "🇲🇫" },
  { code: "SX", dial: "+1", fr: "Saint-Martin (partie néerlandaise)", en: "Sint Maarten", flag: "🇸🇽" },
  { code: "PM", dial: "+508", fr: "Saint-Pierre-et-Miquelon", en: "St. Pierre & Miquelon", flag: "🇵🇲" },
  { code: "VC", dial: "+1", fr: "Saint-Vincent-et-les Grenadines", en: "St. Vincent & Grenadines", flag: "🇻🇨" },
  { code: "SH", dial: "+290", fr: "Sainte-Hélène", en: "St. Helena", flag: "🇸🇭" },
  { code: "LC", dial: "+1", fr: "Sainte-Lucie", en: "St. Lucia", flag: "🇱🇨" },
  { code: "SV", dial: "+503", fr: "Salvador", en: "El Salvador", flag: "🇸🇻" },
  { code: "WS", dial: "+685", fr: "Samoa", en: "Samoa", flag: "🇼🇸" },
  { code: "AS", dial: "+1", fr: "Samoa américaines", en: "American Samoa", flag: "🇦🇸" },
  { code: "ST", dial: "+239", fr: "Sao Tomé-et-Principe", en: "São Tomé & Príncipe", flag: "🇸🇹" },
  { code: "SN", dial: "+221", fr: "Sénégal", en: "Senegal", flag: "🇸🇳" },
  { code: "RS", dial: "+381", fr: "Serbie", en: "Serbia", flag: "🇷🇸" },
  { code: "SC", dial: "+248", fr: "Seychelles", en: "Seychelles", flag: "🇸🇨" },
  { code: "SL", dial: "+232", fr: "Sierra Leone", en: "Sierra Leone", flag: "🇸🇱" },
  { code: "SG", dial: "+65", fr: "Singapour", en: "Singapore", flag: "🇸🇬" },
  { code: "SK", dial: "+421", fr: "Slovaquie", en: "Slovakia", flag: "🇸🇰" },
  { code: "SI", dial: "+386", fr: "Slovénie", en: "Slovenia", flag: "🇸🇮" },
  { code: "SO", dial: "+252", fr: "Somalie", en: "Somalia", flag: "🇸🇴" },
  { code: "SD", dial: "+249", fr: "Soudan", en: "Sudan", flag: "🇸🇩" },
  { code: "SS", dial: "+211", fr: "Soudan du Sud", en: "South Sudan", flag: "🇸🇸" },
  { code: "LK", dial: "+94", fr: "Sri Lanka", en: "Sri Lanka", flag: "🇱🇰" },
  { code: "SE", dial: "+46", fr: "Suède", en: "Sweden", flag: "🇸🇪" },
  { code: "CH", dial: "+41", fr: "Suisse", en: "Switzerland", flag: "🇨🇭" },
  { code: "SR", dial: "+597", fr: "Suriname", en: "Suriname", flag: "🇸🇷" },
  { code: "SJ", dial: "+47", fr: "Svalbard et Jan Mayen", en: "Svalbard & Jan Mayen", flag: "🇸🇯" },
  { code: "SY", dial: "+963", fr: "Syrie", en: "Syria", flag: "🇸🇾" },
  { code: "TJ", dial: "+992", fr: "Tadjikistan", en: "Tajikistan", flag: "🇹🇯" },
  { code: "TW", dial: "+886", fr: "Taïwan", en: "Taiwan", flag: "🇹🇼" },
  { code: "TZ", dial: "+255", fr: "Tanzanie", en: "Tanzania", flag: "🇹🇿" },
  { code: "TD", dial: "+235", fr: "Tchad", en: "Chad", flag: "🇹🇩" },
  { code: "CZ", dial: "+420", fr: "Tchéquie", en: "Czechia", flag: "🇨🇿" },
  { code: "IO", dial: "+246", fr: "Territoire britannique de l’océan Indien", en: "British Indian Ocean Territory", flag: "🇮🇴" },
  { code: "PS", dial: "+970", fr: "Territoires palestiniens", en: "Palestinian Territories", flag: "🇵🇸" },
  { code: "TH", dial: "+66", fr: "Thaïlande", en: "Thailand", flag: "🇹🇭" },
  { code: "TL", dial: "+670", fr: "Timor oriental", en: "Timor-Leste", flag: "🇹🇱" },
  { code: "TG", dial: "+228", fr: "Togo", en: "Togo", flag: "🇹🇬" },
  { code: "TK", dial: "+690", fr: "Tokelau", en: "Tokelau", flag: "🇹🇰" },
  { code: "TO", dial: "+676", fr: "Tonga", en: "Tonga", flag: "🇹🇴" },
  { code: "TT", dial: "+1", fr: "Trinité-et-Tobago", en: "Trinidad & Tobago", flag: "🇹🇹" },
  { code: "TA", dial: "+290", fr: "Tristan da Cunha", en: "Tristan da Cunha", flag: "🇹🇦" },
  { code: "TN", dial: "+216", fr: "Tunisie", en: "Tunisia", flag: "🇹🇳" },
  { code: "TM", dial: "+993", fr: "Turkménistan", en: "Turkmenistan", flag: "🇹🇲" },
  { code: "TR", dial: "+90", fr: "Turquie", en: "Türkiye", flag: "🇹🇷" },
  { code: "TV", dial: "+688", fr: "Tuvalu", en: "Tuvalu", flag: "🇹🇻" },
  { code: "UA", dial: "+380", fr: "Ukraine", en: "Ukraine", flag: "🇺🇦" },
  { code: "UY", dial: "+598", fr: "Uruguay", en: "Uruguay", flag: "🇺🇾" },
  { code: "VU", dial: "+678", fr: "Vanuatu", en: "Vanuatu", flag: "🇻🇺" },
  { code: "VE", dial: "+58", fr: "Venezuela", en: "Venezuela", flag: "🇻🇪" },
  { code: "VN", dial: "+84", fr: "Viêt Nam", en: "Vietnam", flag: "🇻🇳" },
  { code: "WF", dial: "+681", fr: "Wallis-et-Futuna", en: "Wallis & Futuna", flag: "🇼🇫" },
  { code: "YE", dial: "+967", fr: "Yémen", en: "Yemen", flag: "🇾🇪" },
  { code: "ZM", dial: "+260", fr: "Zambie", en: "Zambia", flag: "🇿🇲" },
  { code: "ZW", dial: "+263", fr: "Zimbabwe", en: "Zimbabwe", flag: "🇿🇼" },
];

export function phoneCountryByCode(code: string | null | undefined): PhoneCountry | undefined {
  if (!code) return undefined;
  const c = code.trim().toUpperCase();
  return PHONE_COUNTRIES.find((x) => x.code === c);
}

/** Numéro complet au format international, ex. +24174825725 */
export function toInternational(countryCode: string, rawPhone: string): string {
  const country = phoneCountryByCode(countryCode);
  const digits = (rawPhone ?? "").replace(/\D/g, "").replace(/^0+/, "");
  if (!digits) return "";
  if (!country) return `+${digits}`;
  const dial = country.dial.replace("+", "");
  return digits.startsWith(dial) ? `+${digits}` : `${country.dial}${digits}`;
}

/** Numéro nettoyé pour un lien wa.me (chiffres uniquement). */
export function toWhatsAppNumber(value: string | null | undefined): string {
  return (value ?? "").replace(/\D/g, "");
}
