/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPaiementRetourRouteImport } from './routes/_authenticated/paiement-retour'
import { Route as AuthenticatedAchatCreditsRouteImport } from './routes/_authenticated/achat-credits'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedResultatIdRouteImport } from './routes/_authenticated/resultat.$id'
import { Route as AuthenticatedAdminCandidatsRouteImport } from './routes/_authenticated/admin/candidats'
import { Route as AuthenticatedAdminAvisRouteImport } from './routes/_authenticated/admin/avis'
import { Route as ApiPublicChariowWebhookSecretRouteImport } from './routes/api/public/chariow-webhook.$secret'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementRetourRoute =
  AuthenticatedPaiementRetourRouteImport.update({
    id: '/paiement-retour',
    path: '/paiement-retour',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAchatCreditsRoute =
  AuthenticatedAchatCreditsRouteImport.update({
    id: '/achat-credits',
    path: '/achat-credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedResultatIdRoute = AuthenticatedResultatIdRouteImport.update({
  id: '/resultat/$id',
  path: '/resultat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCandidatsRoute =
  AuthenticatedAdminCandidatsRouteImport.update({
    id: '/candidats',
    path: '/candidats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvisRoute = AuthenticatedAdminAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicChariowWebhookSecretRoute =
  ApiPublicChariowWebhookSecretRouteImport.update({
    id: '/api/public/chariow-webhook/$secret',
    path: '/api/public/chariow-webhook/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/achat-credits': typeof AuthenticatedAchatCreditsRoute
  '/paiement-retour': typeof AuthenticatedPaiementRetourRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/test': typeof AuthenticatedTestRoute
  '/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/admin/candidats': typeof AuthenticatedAdminCandidatsRoute
  '/resultat/$id': typeof AuthenticatedResultatIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/chariow-webhook/$secret': typeof ApiPublicChariowWebhookSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achat-credits': typeof AuthenticatedAchatCreditsRoute
  '/paiement-retour': typeof AuthenticatedPaiementRetourRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/test': typeof AuthenticatedTestRoute
  '/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/admin/candidats': typeof AuthenticatedAdminCandidatsRoute
  '/resultat/$id': typeof AuthenticatedResultatIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/chariow-webhook/$secret': typeof ApiPublicChariowWebhookSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/achat-credits': typeof AuthenticatedAchatCreditsRoute
  '/_authenticated/paiement-retour': typeof AuthenticatedPaiementRetourRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/_authenticated/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/_authenticated/admin/candidats': typeof AuthenticatedAdminCandidatsRoute
  '/_authenticated/resultat/$id': typeof AuthenticatedResultatIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/chariow-webhook/$secret': typeof ApiPublicChariowWebhookSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/achat-credits'
    | '/paiement-retour'
    | '/profil'
    | '/tableau-de-bord'
    | '/test'
    | '/admin/avis'
    | '/admin/candidats'
    | '/resultat/$id'
    | '/admin/'
    | '/api/public/chariow-webhook/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achat-credits'
    | '/paiement-retour'
    | '/profil'
    | '/tableau-de-bord'
    | '/test'
    | '/admin/avis'
    | '/admin/candidats'
    | '/resultat/$id'
    | '/admin'
    | '/api/public/chariow-webhook/$secret'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/achat-credits'
    | '/_authenticated/paiement-retour'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/test'
    | '/_authenticated/admin/avis'
    | '/_authenticated/admin/candidats'
    | '/_authenticated/resultat/$id'
    | '/_authenticated/admin/'
    | '/api/public/chariow-webhook/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicChariowWebhookSecretRoute: typeof ApiPublicChariowWebhookSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiement-retour': {
      id: '/_authenticated/paiement-retour'
      path: '/paiement-retour'
      fullPath: '/paiement-retour'
      preLoaderRoute: typeof AuthenticatedPaiementRetourRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achat-credits': {
      id: '/_authenticated/achat-credits'
      path: '/achat-credits'
      fullPath: '/achat-credits'
      preLoaderRoute: typeof AuthenticatedAchatCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/resultat/$id': {
      id: '/_authenticated/resultat/$id'
      path: '/resultat/$id'
      fullPath: '/resultat/$id'
      preLoaderRoute: typeof AuthenticatedResultatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/candidats': {
      id: '/_authenticated/admin/candidats'
      path: '/candidats'
      fullPath: '/admin/candidats'
      preLoaderRoute: typeof AuthenticatedAdminCandidatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/avis': {
      id: '/_authenticated/admin/avis'
      path: '/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AuthenticatedAdminAvisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/chariow-webhook/$secret': {
      id: '/api/public/chariow-webhook/$secret'
      path: '/api/public/chariow-webhook/$secret'
      fullPath: '/api/public/chariow-webhook/$secret'
      preLoaderRoute: typeof ApiPublicChariowWebhookSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAvisRoute: typeof AuthenticatedAdminAvisRoute
  AuthenticatedAdminCandidatsRoute: typeof AuthenticatedAdminCandidatsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAvisRoute: AuthenticatedAdminAvisRoute,
    AuthenticatedAdminCandidatsRoute: AuthenticatedAdminCandidatsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAchatCreditsRoute: typeof AuthenticatedAchatCreditsRoute
  AuthenticatedPaiementRetourRoute: typeof AuthenticatedPaiementRetourRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedResultatIdRoute: typeof AuthenticatedResultatIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAchatCreditsRoute: AuthenticatedAchatCreditsRoute,
  AuthenticatedPaiementRetourRoute: AuthenticatedPaiementRetourRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedResultatIdRoute: AuthenticatedResultatIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicChariowWebhookSecretRoute: ApiPublicChariowWebhookSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
