/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as CertifiesRouteImport } from './routes/certifies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPaiementRetourRouteImport } from './routes/_authenticated/paiement-retour'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedClassementRouteImport } from './routes/_authenticated/classement'
import { Route as AuthenticatedAchatCreditsRouteImport } from './routes/_authenticated/achat-credits'
import { Route as AuthenticatedAccomplissementsRouteImport } from './routes/_authenticated/accomplissements'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedResultatIdRouteImport } from './routes/_authenticated/resultat.$id'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin/utilisateurs'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin/journal'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminCertificatsRouteImport } from './routes/_authenticated/admin/certificats'
import { Route as AuthenticatedAdminCandidatsRouteImport } from './routes/_authenticated/admin/candidats'
import { Route as AuthenticatedAdminAvisRouteImport } from './routes/_authenticated/admin/avis'
import { Route as ApiPublicChariowWebhookSecretRouteImport } from './routes/api/public/chariow-webhook.$secret'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifiesRoute = CertifiesRouteImport.update({
  id: '/certifies',
  path: '/certifies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementRetourRoute =
  AuthenticatedPaiementRetourRouteImport.update({
    id: '/paiement-retour',
    path: '/paiement-retour',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassementRoute = AuthenticatedClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchatCreditsRoute =
  AuthenticatedAchatCreditsRouteImport.update({
    id: '/achat-credits',
    path: '/achat-credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccomplissementsRoute =
  AuthenticatedAccomplissementsRouteImport.update({
    id: '/accomplissements',
    path: '/accomplissements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedResultatIdRoute = AuthenticatedResultatIdRouteImport.update({
  id: '/resultat/$id',
  path: '/resultat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCertificatsRoute =
  AuthenticatedAdminCertificatsRouteImport.update({
    id: '/certificats',
    path: '/certificats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCandidatsRoute =
  AuthenticatedAdminCandidatsRouteImport.update({
    id: '/candidats',
    path: '/candidats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvisRoute = AuthenticatedAdminAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicChariowWebhookSecretRoute =
  ApiPublicChariowWebhookSecretRouteImport.update({
    id: '/api/public/chariow-webhook/$secret',
    path: '/api/public/chariow-webhook/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certifies': typeof CertifiesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/accomplissements': typeof AuthenticatedAccomplissementsRoute
  '/achat-credits': typeof AuthenticatedAchatCreditsRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/paiement-retour': typeof AuthenticatedPaiementRetourRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/test': typeof AuthenticatedTestRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/admin/candidats': typeof AuthenticatedAdminCandidatsRoute
  '/admin/certificats': typeof AuthenticatedAdminCertificatsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/resultat/$id': typeof AuthenticatedResultatIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/chariow-webhook/$secret': typeof ApiPublicChariowWebhookSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certifies': typeof CertifiesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accomplissements': typeof AuthenticatedAccomplissementsRoute
  '/achat-credits': typeof AuthenticatedAchatCreditsRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/paiement-retour': typeof AuthenticatedPaiementRetourRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/test': typeof AuthenticatedTestRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/admin/candidats': typeof AuthenticatedAdminCandidatsRoute
  '/admin/certificats': typeof AuthenticatedAdminCertificatsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/resultat/$id': typeof AuthenticatedResultatIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/chariow-webhook/$secret': typeof ApiPublicChariowWebhookSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/certifies': typeof CertifiesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/accomplissements': typeof AuthenticatedAccomplissementsRoute
  '/_authenticated/achat-credits': typeof AuthenticatedAchatCreditsRoute
  '/_authenticated/classement': typeof AuthenticatedClassementRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/paiement-retour': typeof AuthenticatedPaiementRetourRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/profile/$id': typeof ProfileIdRoute
  '/_authenticated/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/_authenticated/admin/candidats': typeof AuthenticatedAdminCandidatsRoute
  '/_authenticated/admin/certificats': typeof AuthenticatedAdminCertificatsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/resultat/$id': typeof AuthenticatedResultatIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/chariow-webhook/$secret': typeof ApiPublicChariowWebhookSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/certifies'
    | '/leaderboards'
    | '/reset-password'
    | '/admin'
    | '/accomplissements'
    | '/achat-credits'
    | '/classement'
    | '/notifications'
    | '/paiement-retour'
    | '/profil'
    | '/tableau-de-bord'
    | '/test'
    | '/profile/$id'
    | '/admin/avis'
    | '/admin/candidats'
    | '/admin/certificats'
    | '/admin/finance'
    | '/admin/journal'
    | '/admin/questions'
    | '/admin/utilisateurs'
    | '/resultat/$id'
    | '/admin/'
    | '/api/public/chariow-webhook/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certifies'
    | '/leaderboards'
    | '/reset-password'
    | '/accomplissements'
    | '/achat-credits'
    | '/classement'
    | '/notifications'
    | '/paiement-retour'
    | '/profil'
    | '/tableau-de-bord'
    | '/test'
    | '/profile/$id'
    | '/admin/avis'
    | '/admin/candidats'
    | '/admin/certificats'
    | '/admin/finance'
    | '/admin/journal'
    | '/admin/questions'
    | '/admin/utilisateurs'
    | '/resultat/$id'
    | '/admin'
    | '/api/public/chariow-webhook/$secret'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/certifies'
    | '/leaderboards'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/accomplissements'
    | '/_authenticated/achat-credits'
    | '/_authenticated/classement'
    | '/_authenticated/notifications'
    | '/_authenticated/paiement-retour'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/test'
    | '/profile/$id'
    | '/_authenticated/admin/avis'
    | '/_authenticated/admin/candidats'
    | '/_authenticated/admin/certificats'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/resultat/$id'
    | '/_authenticated/admin/'
    | '/api/public/chariow-webhook/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CertifiesRoute: typeof CertifiesRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ApiPublicChariowWebhookSecretRoute: typeof ApiPublicChariowWebhookSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifies': {
      id: '/certifies'
      path: '/certifies'
      fullPath: '/certifies'
      preLoaderRoute: typeof CertifiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiement-retour': {
      id: '/_authenticated/paiement-retour'
      path: '/paiement-retour'
      fullPath: '/paiement-retour'
      preLoaderRoute: typeof AuthenticatedPaiementRetourRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classement': {
      id: '/_authenticated/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof AuthenticatedClassementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achat-credits': {
      id: '/_authenticated/achat-credits'
      path: '/achat-credits'
      fullPath: '/achat-credits'
      preLoaderRoute: typeof AuthenticatedAchatCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accomplissements': {
      id: '/_authenticated/accomplissements'
      path: '/accomplissements'
      fullPath: '/accomplissements'
      preLoaderRoute: typeof AuthenticatedAccomplissementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/resultat/$id': {
      id: '/_authenticated/resultat/$id'
      path: '/resultat/$id'
      fullPath: '/resultat/$id'
      preLoaderRoute: typeof AuthenticatedResultatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/certificats': {
      id: '/_authenticated/admin/certificats'
      path: '/certificats'
      fullPath: '/admin/certificats'
      preLoaderRoute: typeof AuthenticatedAdminCertificatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/candidats': {
      id: '/_authenticated/admin/candidats'
      path: '/candidats'
      fullPath: '/admin/candidats'
      preLoaderRoute: typeof AuthenticatedAdminCandidatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/avis': {
      id: '/_authenticated/admin/avis'
      path: '/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AuthenticatedAdminAvisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/chariow-webhook/$secret': {
      id: '/api/public/chariow-webhook/$secret'
      path: '/api/public/chariow-webhook/$secret'
      fullPath: '/api/public/chariow-webhook/$secret'
      preLoaderRoute: typeof ApiPublicChariowWebhookSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAvisRoute: typeof AuthenticatedAdminAvisRoute
  AuthenticatedAdminCandidatsRoute: typeof AuthenticatedAdminCandidatsRoute
  AuthenticatedAdminCertificatsRoute: typeof AuthenticatedAdminCertificatsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAvisRoute: AuthenticatedAdminAvisRoute,
    AuthenticatedAdminCandidatsRoute: AuthenticatedAdminCandidatsRoute,
    AuthenticatedAdminCertificatsRoute: AuthenticatedAdminCertificatsRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccomplissementsRoute: typeof AuthenticatedAccomplissementsRoute
  AuthenticatedAchatCreditsRoute: typeof AuthenticatedAchatCreditsRoute
  AuthenticatedClassementRoute: typeof AuthenticatedClassementRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaiementRetourRoute: typeof AuthenticatedPaiementRetourRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedResultatIdRoute: typeof AuthenticatedResultatIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccomplissementsRoute: AuthenticatedAccomplissementsRoute,
  AuthenticatedAchatCreditsRoute: AuthenticatedAchatCreditsRoute,
  AuthenticatedClassementRoute: AuthenticatedClassementRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaiementRetourRoute: AuthenticatedPaiementRetourRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedResultatIdRoute: AuthenticatedResultatIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CertifiesRoute: CertifiesRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProfileIdRoute: ProfileIdRoute,
  ApiPublicChariowWebhookSecretRoute: ApiPublicChariowWebhookSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
