INSERT INTO public.questions (level, category, question_type, question_text, options, correct_answer, explanation, language, is_active, order_hint, points, max_plays) VALUES

-- B1 WRITING
('B1','writing','writing','Un amigo le ha preguntado por qué estudia español. Escriba un mensaje (120 a 150 palabras) en el que explique: cómo descubrió la plataforma de evaluación OpenDoorsClass, que ofrece pruebas de nivel en línea, por qué decidió medir su nivel de español, y qué espera conseguir en los próximos meses. Organice sus ideas y utilice conectores.','[]'::jsonb,'','Se evalúa la organización de las ideas, la riqueza del vocabulario, la corrección gramatical y la capacidad de comunicar objetivos personales.','es',true,1,1,5),
('B1','writing','writing','Cuente una experiencia de aprendizaje que le haya marcado (un curso, un viaje, una clase difícil). Escriba un texto de 120 a 150 palabras: describa la situación, explique qué ocurrió, cómo se sintió y qué aprendió de esa experiencia. Utilice tiempos del pasado.','[]'::jsonb,'','Se evalúa el uso correcto del pretérito indefinido y del imperfecto, la coherencia narrativa y la claridad de la reflexión final.','es',true,2,1,5),
('B1','writing','writing','Usted quiere participar en un intercambio lingüístico en un país hispanohablante. Escriba un correo (130 a 160 palabras) al responsable del programa: preséntese, explique su nivel actual de español, indique sus motivaciones y pregunte por el alojamiento y el horario de las clases.','[]'::jsonb,'','Se evalúa el registro semiformal, la estructura del correo, la precisión gramatical y la capacidad de formular preguntas claras.','es',true,3,1,5),

-- B1 SPEAKING
('B1','speaking','speaking','Hable durante uno o dos minutos sobre su experiencia aprendiendo idiomas: qué lenguas ha estudiado, qué métodos le han funcionado mejor y qué dificultades ha encontrado. Termine explicando qué consejo daría a alguien que empieza.','[]'::jsonb,'','Se evalúa la fluidez, la organización del discurso, el vocabulario del ámbito educativo y el uso de tiempos del pasado y del presente.','es',true,2,1,5),
('B1','speaking','speaking','Explique por qué ha decidido aprender español y qué le gustaría lograr con este idioma: en los estudios, en el trabajo o en sus viajes. Dé al menos dos ejemplos concretos y hable durante uno o dos minutos.','[]'::jsonb,'','Se evalúa la capacidad de expresar intenciones y proyectos, la coherencia y la precisión gramatical.','es',true,3,1,5),
('B1','speaking','speaking','Imagine que un amigo duda entre estudiar solo o unirse a una comunidad de aprendizaje en línea, como la que propone OpenDoorsClass, donde los estudiantes practican juntos después de una prueba de nivel. Explíquele las ventajas de aprender acompañado y dé su opinión personal.','[]'::jsonb,'','Se evalúa la capacidad de aconsejar, comparar dos opciones y justificar una opinión con ejemplos.','es',true,4,1,5),

-- B2 WRITING
('B2','writing','writing','Un centro de formación quiere evaluar el nivel lingüístico de sus alumnos con una plataforma externa antes de la inscripción. Redacte un texto argumentativo de 180 a 220 palabras en el que exponga las ventajas y los límites de esta práctica, y proponga una recomendación final justificada.','[]'::jsonb,'','Se evalúa la argumentación equilibrada, el uso de conectores lógicos, la precisión léxica y la formulación de una conclusión razonada.','es',true,1,1,5),
('B2','writing','writing','Escriba un artículo de opinión (180 a 220 palabras) para la revista de su universidad sobre esta pregunta: ¿las redes sociales ayudan realmente a aprender idiomas o distraen más de lo que enseñan? Defienda su postura con al menos tres argumentos y responda a una objeción posible.','[]'::jsonb,'','Se evalúa la capacidad de argumentar, de refutar una objeción, la variedad sintáctica y la adecuación del registro periodístico.','es',true,2,1,5),
('B2','writing','writing','Su empresa estudia sustituir las formaciones presenciales por cursos en línea para reducir costes. Redacte un informe interno de 200 a 240 palabras dirigido a su responsable: analice las consecuencias para los empleados, compare las dos modalidades y proponga una solución intermedia.','[]'::jsonb,'','Se evalúa el registro profesional, la estructura del informe, la comparación argumentada y la precisión gramatical.','es',true,3,1,5),

-- B2 SPEAKING
('B2','speaking','speaking','Muchos consideran que los cursos en línea podrán sustituir por completo a las clases presenciales. Exprese su opinión durante dos o tres minutos: compare ambas modalidades, aporte argumentos a favor y en contra, y defienda una postura clara.','[]'::jsonb,'','Se evalúa la capacidad de comparar, matizar y sostener una postura con argumentos encadenados.','es',true,1,1,5),
('B2','speaking','speaking','Un amigo quiere inscribirse directamente en un curso avanzado sin hacer antes una prueba de nivel. Explíquele por qué evaluar el nivel antes de empezar una formación puede ser útil, y reconozca también los límites de este tipo de pruebas.','[]'::jsonb,'','Se evalúa la argumentación, la concesión, el uso del subjuntivo y la claridad expositiva.','es',true,2,1,5),
('B2','speaking','speaking','¿Debería ser obligatorio dominar al menos dos lenguas extranjeras para acceder a determinados empleos? Desarrolle su punto de vista durante dos o tres minutos, con ejemplos del mundo laboral y una conclusión personal.','[]'::jsonb,'','Se evalúa la profundidad argumentativa, la riqueza léxica y la capacidad de reaccionar ante una cuestión polémica.','es',true,3,1,5),

-- C1 ORTHOGRAPHY
('C1','orthography','mcq','Elija la frase escrita correctamente.','["Aún no sé si vendrá, pero, si lo hace, avísame.","Aun no sé si vendrá, pero, si lo hace, avisame.","Aún no se si vendrá, pero si lo hace avísame.","Aun nó sé si vendra, pero si lo hace, avísame."]'::jsonb,'Aún no sé si vendrá, pero, si lo hace, avísame.','« Aún » con tilde equivale a « todavía », « sé » del verbo saber lleva tilde diacrítica y « avísame » es esdrújula, por lo que se acentúa.','es',true,1,1,5),
('C1','orthography','mcq','Seleccione la opción correcta: « El comité decidió ____ el proyecto porque ____ los plazos previstos. »','["posponer / excedía","pospooner / exedía","posponner / excedia","pospner / eccedía"]'::jsonb,'posponer / excedía','« Posponer » se escribe con una sola « n » interior y « excedía » conserva el grupo « xc » y la tilde del imperfecto en hiato.','es',true,2,1,5),
('C1','orthography','mcq','¿Cuál de estas frases es ortográficamente correcta?','["Hizo el trabajo a conciencia, sin que nadie se lo pidiera.","Hizo el trabajo aconciencia, sin que nadie se lo pidiera.","Izo el trabajo a conciencia, sin que nadie se lo pidiera.","Hizo el travajo a conciencia, sin que nadie se lo pidiera."]'::jsonb,'Hizo el trabajo a conciencia, sin que nadie se lo pidiera.','La locución « a conciencia » se escribe separada; « hizo » del verbo hacer se escribe con hache, a diferencia de « izo », de izar.','es',true,3,1,5),
('C1','orthography','mcq','Elija la forma correcta: « Espero que ____ razón, ____ que las cifras dicen lo contrario. »','["tengas / a pesar de","tengas / apesar de","tengás / a pesar de","tenga / halgo pesar de"]'::jsonb,'tengas / a pesar de','« A pesar de » es una locución que siempre se escribe separada, y « tengas » es la forma correcta del presente de subjuntivo, sin tilde.','es',true,4,1,5),

-- C1 READING
('C1','reading','mcq','Lea el texto: « Durante años, las instituciones educativas midieron el progreso de sus alumnos casi exclusivamente mediante exámenes finales. Hoy, las plataformas digitales permiten evaluar de forma continua, lo que muchos celebran como un avance indiscutible. Sin embargo, conviene recordar que un dato no es un diagnóstico: acumular resultados no equivale a comprender por qué un estudiante avanza o se estanca. La tecnología ha ampliado nuestra capacidad de medir, no necesariamente la de interpretar. » ¿Cuál es la idea central del autor?','["La abundancia de datos no garantiza una mejor comprensión del aprendizaje.","Los exámenes finales siguen siendo el único método fiable de evaluación.","Las plataformas digitales han sustituido con éxito a los profesores.","La evaluación continua debería prohibirse en las instituciones educativas."]'::jsonb,'La abundancia de datos no garantiza una mejor comprensión del aprendizaje.','El autor contrapone medir e interpretar: reconoce el avance técnico pero advierte que los datos por sí solos no explican el proceso de aprendizaje.','es',true,1,1,5),
('C1','reading','mcq','Lea el texto: « Se repite que aprender una lengua abre puertas. La afirmación es cierta, aunque incompleta. Quien domina un idioma sin conocer los códigos culturales que lo rodean puede pronunciar frases impecables y, aun así, resultar torpe en una negociación. El vocabulario se memoriza; la pertinencia se aprende conviviendo. » ¿Qué actitud adopta el autor frente a la afirmación inicial?','["La matiza señalando que el dominio lingüístico no basta sin competencia cultural.","La rechaza porque considera inútil aprender lenguas extranjeras.","La confirma sin reservas y añade ejemplos favorables.","La ridiculiza al presentarla como un mito sin ningún fundamento."]'::jsonb,'La matiza señalando que el dominio lingüístico no basta sin competencia cultural.','El autor admite que la afirmación es cierta pero la califica de incompleta, lo que indica un matiz y no un rechazo.','es',true,2,1,5),
('C1','reading','mcq','Lea el texto: « Plataformas como OpenDoorsClass proponen una prueba de nivel previa a cualquier formación. La lógica es sencilla: situar al estudiante en el punto exacto donde debe empezar evita tanto la frustración como el aburrimiento. Ahora bien, ninguna prueba capta la motivación, y es esta, más que el nivel inicial, la que suele decidir el desenlace de un curso. » Según el texto, ¿cuál es la principal limitación de estas pruebas?','["No pueden medir un factor decisivo como la motivación del estudiante.","Colocan a los estudiantes en niveles siempre demasiado altos.","Resultan demasiado caras para la mayoría de los centros.","Sustituyen la enseñanza presencial por cursos automatizados."]'::jsonb,'No pueden medir un factor decisivo como la motivación del estudiante.','El texto reconoce la utilidad de situar el nivel, pero señala explícitamente que la motivación escapa a la prueba y suele ser determinante.','es',true,3,1,5),
('C1','reading','mcq','Lea el texto: « El teletrabajo se presentó como una conquista para el empleado. Pocos previeron que la desaparición del trayecto diario borraría también la frontera que separaba la oficina del salón. La flexibilidad prometida se ha convertido, para algunos, en una disponibilidad permanente. » ¿Qué sugiere el autor sobre la flexibilidad del teletrabajo?','["Que puede transformarse en una forma de disponibilidad continua.","Que ha mejorado el equilibrio personal de todos los empleados.","Que resulta imposible de aplicar en las empresas actuales.","Que solo beneficia a quienes viven lejos de la oficina."]'::jsonb,'Que puede transformarse en una forma de disponibilidad continua.','La última frase opone la flexibilidad prometida a la disponibilidad permanente, señal de una consecuencia no prevista.','es',true,4,1,5),

-- C1 WRITING
('C1','writing','writing','Redacte un ensayo argumentativo de 250 a 300 palabras sobre el papel de las lenguas en la movilidad internacional: ¿favorecen realmente la igualdad de oportunidades o refuerzan las desigualdades existentes? Estructure su texto en introducción, desarrollo matizado y conclusión.','[]'::jsonb,'','Se evalúa la estructura del ensayo, la capacidad de matizar, la densidad argumentativa y la precisión léxica y gramatical.','es',true,1,1,5),
('C1','writing','writing','Una organización desea implantar una evaluación lingüística previa a la entrada en sus formaciones. Redacte una propuesta razonada de 250 a 300 palabras dirigida a su dirección: justifique la utilidad de la medida, anticipe las objeciones y proponga condiciones concretas de aplicación.','[]'::jsonb,'','Se evalúa el registro profesional, la anticipación de objeciones, la organización lógica y el uso de estructuras complejas.','es',true,2,1,5),
('C1','writing','writing','La inteligencia artificial permite hoy corregir, traducir y practicar idiomas de forma automática. Redacte un texto de 250 a 300 palabras en el que analice en qué medida esta tecnología transforma el aprendizaje y qué competencias humanas siguen siendo insustituibles.','[]'::jsonb,'','Se evalúa la capacidad de análisis, la nuance en el juicio crítico y el dominio de conectores complejos.','es',true,3,1,5),

-- C1 SPEAKING
('C1','speaking','speaking','Desarrolle durante tres o cuatro minutos esta cuestión: ¿la tecnología está democratizando el acceso a la educación o creando nuevas formas de exclusión? Presente argumentos contrapuestos y defienda una posición matizada.','[]'::jsonb,'','Se evalúa la capacidad de estructurar un discurso extenso, matizar y sostener una tesis con contraargumentos.','es',true,1,1,5),
('C1','speaking','speaking','Le piden intervenir en una mesa redonda sobre el futuro del aprendizaje de idiomas. Exponga durante tres minutos cómo imagina la enseñanza de lenguas dentro de diez años y qué riesgos conviene anticipar.','[]'::jsonb,'','Se evalúa la proyección argumentada, la riqueza léxica y el uso de estructuras hipotéticas.','es',true,2,1,5),
('C1','speaking','speaking','Algunos afirman que las pruebas de nivel, como las que ofrecen las plataformas de evaluación en línea, reducen a una cifra algo tan complejo como una competencia lingüística. Analice esta crítica: ¿hasta qué punto está justificada? Defienda su análisis con ejemplos.','[]'::jsonb,'','Se evalúa el análisis crítico, la capacidad de conceder y refutar, y la fluidez en un registro formal.','es',true,3,1,5),

-- C2 ORTHOGRAPHY
('C2','orthography','mcq','Elija la única frase correcta.','["Por qué no vino es algo que aún ignoramos; el porqué de su silencio, también.","Porqué no vino es algo que aún ignoramos; el por qué de su silencio, también.","Por que no vino es algo que aun ignoramos; el porque de su silencio, también.","Porque no vino es algo que aún ignoramos; el porqué de su silencio, tanbién."]'::jsonb,'Por qué no vino es algo que aún ignoramos; el porqué de su silencio, también.','« Por qué » interrogativo se escribe separado y con tilde; « el porqué » sustantivo se escribe junto y con tilde.','es',true,1,1,5),
('C2','orthography','mcq','Seleccione la forma correcta: « El informe fue ____ por el comité, que ____ varias irregularidades. »','["rehecho / entrevió","reecho / entrevió","rehecho / entreveyó","reheho / entreveió"]'::jsonb,'rehecho / entrevió','« Rehecho » conserva la hache del verbo hacer tras el prefijo, y el pretérito de entrever es « entrevió », sin diptongo añadido.','es',true,2,1,5),
('C2','orthography','mcq','¿Cuál de estas frases respeta la norma ortográfica?','["Se lo dije asimismo a ella, y a sí mismo se lo repitió él.","Se lo dije así mismo a ella, y asimismo se lo repitió él a sí mismo.","Se lo dije a si mismo a ella, y asímismo se lo repitió él.","Se lo dije asímismo a ella, y a simismo se lo repitió él."]'::jsonb,'Se lo dije asimismo a ella, y a sí mismo se lo repitió él.','« Asimismo » equivale a « también »; « a sí mismo » es la secuencia con pronombre reflexivo y se escribe separada y con tilde.','es',true,3,1,5),
('C2','orthography','mcq','Elija la opción correcta: « La conferencia fue ____ ; ____ los asistentes salieron convencidos. »','["excepcional / con todo, no todos","ecepcional / contodo, no todos","excepccional / con todo no, todos","excepcional / contodo no todos"]'::jsonb,'excepcional / con todo, no todos','« Excepcional » mantiene el grupo « xc » y la locución concesiva « con todo » se escribe separada y va seguida de coma.','es',true,4,1,5),

-- C2 READING
('C2','reading','mcq','Lea el texto: « Nada halaga tanto a una época como oírse llamar innovadora. Cada generación descubre, con emoción sincera, que sus herramientas van a transformar definitivamente la enseñanza, y cada generación olvida que la anterior dijo exactamente lo mismo de la radio, del televisor y del proyector de diapositivas. No se trata de negar el progreso, sino de recordar que el entusiasmo rara vez ha sido un buen método pedagógico. » ¿Qué tono predomina en el fragmento?','["Irónico y escéptico ante el entusiasmo tecnológico recurrente.","Nostálgico y opuesto a cualquier forma de innovación educativa.","Neutro y meramente descriptivo de la historia de la enseñanza.","Elogioso hacia las herramientas digitales contemporáneas."]'::jsonb,'Irónico y escéptico ante el entusiasmo tecnológico recurrente.','La comparación con la radio y el proyector, junto con la fórmula final, revela una ironía dirigida al entusiasmo repetido, sin negar el progreso.','es',true,1,1,5),
('C2','reading','mcq','Lea el texto: « Se suele sostener que el mercado laboral recompensa el mérito. La afirmación resulta difícil de refutar precisamente porque es difícil de comprobar: quien triunfa aporta su éxito como prueba de su mérito, y quien fracasa rara vez dispone de tribuna para exponer lo contrario. Una tesis que solo admite testigos favorables no es una verdad, es un procedimiento. » ¿Qué critica exactamente el autor?','["Que la tesis del mérito se sostenga sobre una selección sesgada de testimonios.","Que el mercado laboral no recompense nunca el esfuerzo individual.","Que los trabajadores fracasados carezcan de formación adecuada.","Que las empresas contraten sin evaluar las competencias reales."]'::jsonb,'Que la tesis del mérito se sostenga sobre una selección sesgada de testimonios.','El autor no niega el mérito: denuncia que la tesis se valide solo con testigos favorables, lo que la convierte en irrefutable por construcción.','es',true,2,1,5),
('C2','reading','mcq','Lea el texto: « La lengua no es un simple vehículo neutro del pensamiento. Al elegir una palabra descartamos otras, y con ellas, matices enteros de la realidad. Quien traduce lo sabe: no existe equivalencia perfecta, solo compromisos aceptables. De ahí que hablar varias lenguas no consista únicamente en decir lo mismo de distintas maneras, sino en aprender a pensar lo que la propia lengua no permitía formular. » ¿Qué conclusión se desprende del texto?','["El multilingüismo amplía las posibilidades de pensamiento, no solo de expresión.","Traducir es un ejercicio mecánico que la técnica resolverá pronto.","Todas las lenguas expresan exactamente los mismos matices.","Aprender lenguas extranjeras empobrece la lengua materna."]'::jsonb,'El multilingüismo amplía las posibilidades de pensamiento, no solo de expresión.','La última frase opone explícitamente « decir lo mismo de distintas maneras » a « pensar lo que la propia lengua no permitía formular ».','es',true,3,1,5),
('C2','reading','mcq','Lea el texto: « Los indicadores educativos gozan de una autoridad que su fragilidad no justifica. Una vez publicada, la cifra circula desprovista de su método, de sus márgenes de error y de las decisiones arbitrarias que la hicieron posible. El número sobrevive; las reservas se pierden por el camino. » ¿Qué implica el autor con la frase final?','["Que la difusión pública de una cifra elimina las cautelas metodológicas que la acompañaban.","Que los indicadores educativos son siempre resultado de un fraude deliberado.","Que conviene renunciar por completo a la medición en educación.","Que los márgenes de error suelen calcularse con excesiva precisión."]'::jsonb,'Que la difusión pública de una cifra elimina las cautelas metodológicas que la acompañaban.','La oposición entre « el número sobrevive » y « las reservas se pierden » señala la pérdida de las precauciones metodológicas al circular el dato.','es',true,4,1,5),

-- C2 WRITING
('C2','writing','writing','Redacte un ensayo crítico de 320 a 380 palabras sobre esta afirmación: « Medir una competencia lingüística con una cifra es siempre una simplificación abusiva. » Discuta la afirmación, examine sus fundamentos y sus límites, y formule una posición personal argumentada.','[]'::jsonb,'','Se evalúa la finura del análisis, la reformulación de la tesis, el control del registro y la precisión sintáctica y léxica.','es',true,1,1,5),
('C2','writing','writing','Una plataforma de evaluación lingüística estudia extender su sistema a varios países con realidades educativas muy distintas. Redacte un análisis de 320 a 380 palabras que exponga las ventajas, los límites y los desafíos culturales, técnicos y éticos de esa expansión, y concluya con recomendaciones jerarquizadas.','[]'::jsonb,'','Se evalúa la capacidad de análisis multidimensional, la jerarquización de las ideas y el dominio del discurso profesional.','es',true,2,1,5),
('C2','writing','writing','Escriba un artículo de opinión de 320 a 380 palabras sobre la siguiente cuestión: ¿la automatización de la corrección y de la traducción amenaza la enseñanza de las lenguas o la obliga a reinventarse? Adopte una postura clara, anticipe las objeciones y cuide el estilo.','[]'::jsonb,'','Se evalúa la originalidad de la argumentación, el control estilístico, la anticipación de objeciones y la corrección formal.','es',true,3,1,5),

-- C2 SPEAKING
('C2','speaking','speaking','Analice durante cuatro o cinco minutos los límites de las pruebas estandarizadas de idiomas: qué miden realmente, qué dejan fuera y en qué condiciones siguen siendo útiles. Sostenga una posición matizada y responda a las objeciones previsibles.','[]'::jsonb,'','Se evalúa la profundidad analítica, la capacidad de anticipar objeciones y la fluidez en un registro académico.','es',true,1,1,5),
('C2','speaking','speaking','Defienda una posición controvertida sobre esta cuestión: ¿debería el Estado financiar plataformas privadas de educación digital? Exponga su tesis, contemple los argumentos contrarios y reformule su posición al final del discurso.','[]'::jsonb,'','Se evalúa la argumentación compleja, la reformulación estratégica y la precisión conceptual.','es',true,2,1,5),
('C2','speaking','speaking','Tome el caso de una plataforma de evaluación lingüística en línea, como OpenDoorsClass, que sitúa a los candidatos en un nivel antes de una formación. Analice el modelo: qué problema resuelve, qué efectos secundarios puede producir y bajo qué condiciones resulta pedagógicamente legítimo.','[]'::jsonb,'','Se evalúa la capacidad de analizar un caso concreto, de identificar efectos no deseados y de formular condiciones de validez.','es',true,3,1,5);