DELETE FROM public.questions WHERE language = 'es';
INSERT INTO public.questions (level, category, question_text, options, correct_answer, order_hint, is_active, question_type, language) VALUES
('A1','grammar','Yo ___ estudiante de español.','["soy", "eres", "es", "somos"]'::jsonb,'soy',1,true,'mcq','es'),
('A1','grammar','Ella ___ en Madrid.','["vive", "vives", "vivo", "viven"]'::jsonb,'vive',2,true,'mcq','es'),
('A1','grammar','___ libros están sobre la mesa.','["Los", "Las", "El", "Un"]'::jsonb,'Los',3,true,'mcq','es'),
('A1','grammar','Nosotros ___ hambre.','["tenemos", "tienen", "tengo", "tiene"]'::jsonb,'tenemos',4,true,'mcq','es'),
('A1','grammar','Mañana yo ___ al mercado.','["voy", "va", "vas", "vamos"]'::jsonb,'voy',5,true,'mcq','es'),
('A1','grammar','Esta es ___ casa. Es de mi familia.','["nuestra", "nuestro", "suyos", "tuyos"]'::jsonb,'nuestra',6,true,'mcq','es'),
('A1','grammar','¿Qué hora ___?','["es", "son", "está", "están"]'::jsonb,'es',7,true,'mcq','es'),
('A1','grammar','A mí ___ gusta el café.','["me", "te", "le", "nos"]'::jsonb,'me',8,true,'mcq','es'),
('A1','grammar','El niño ___ jugando en el parque.','["está", "es", "están", "son"]'::jsonb,'está',9,true,'mcq','es'),
('A1','grammar','No tengo ___ dinero.','["nada de", "ninguno", "nadie", "ningún"]'::jsonb,'nada de',10,true,'mcq','es'),
('A1','vocabulary','¿Qué palabra significa « water » ?','["agua", "fuego", "tierra", "aire"]'::jsonb,'agua',1,true,'mcq','es'),
('A1','vocabulary','El lugar donde compramos pan se llama:','["panadería", "librería", "zapatería", "ferretería"]'::jsonb,'panadería',2,true,'mcq','es'),
('A1','vocabulary','¿Qué día viene después del lunes?','["martes", "domingo", "sábado", "jueves"]'::jsonb,'martes',3,true,'mcq','es'),
('A1','vocabulary','¿Qué palabra es un color?','["verde", "mesa", "perro", "cinco"]'::jsonb,'verde',4,true,'mcq','es'),
('A1','vocabulary','Para escribir necesitamos un:','["bolígrafo", "tenedor", "peine", "cuchillo"]'::jsonb,'bolígrafo',5,true,'mcq','es'),
('A1','vocabulary','El contrario de « grande » es:','["pequeño", "alto", "gordo", "largo"]'::jsonb,'pequeño',6,true,'mcq','es'),
('A1','vocabulary','En la cocina usamos una:','["sartén", "almohada", "corbata", "maleta"]'::jsonb,'sartén',7,true,'mcq','es'),
('A1','vocabulary','¿Qué palabra designa a un familiar?','["hermana", "ventana", "camisa", "carretera"]'::jsonb,'hermana',8,true,'mcq','es'),
('A1','reading','Lea: « Hola, me llamo Ana. Tengo veinte años y vivo en Sevilla con mi madre. » ¿Dónde vive Ana?','["En Sevilla", "En Madrid", "En Lima", "En Bogotá"]'::jsonb,'En Sevilla',1,true,'mcq','es'),
('A1','reading','Lea: « La tienda abre de lunes a viernes, de nueve a dos. » ¿La tienda abre el domingo?','["No, está cerrada", "Sí, todo el día", "Sí, por la tarde", "Solo por la mañana"]'::jsonb,'No, está cerrada',2,true,'mcq','es'),
('A1','reading','Lea: « Carlos toma el autobús a las siete y llega al trabajo a las ocho. » ¿Cuánto dura el viaje?','["Una hora", "Media hora", "Dos horas", "Quince minutos"]'::jsonb,'Una hora',3,true,'mcq','es'),
('A1','reading','Lea: « Se vende bicicleta usada, cincuenta euros. Llamar por la tarde. » ¿Qué se vende?','["Una bicicleta", "Un coche", "Una moto", "Un teléfono"]'::jsonb,'Una bicicleta',4,true,'mcq','es'),
('A1','orthography','¿Qué palabra está bien escrita?','["corazón", "corasón", "corazzón", "corasson"]'::jsonb,'corazón',1,true,'mcq','es'),
('A1','orthography','¿Qué palabra está bien escrita?','["ventana", "bentana", "ventanna", "venttana"]'::jsonb,'ventana',2,true,'mcq','es'),
('A1','orthography','¿Qué palabra está bien escrita?','["escuela", "eskuela", "escuella", "esquela"]'::jsonb,'escuela',3,true,'mcq','es'),
('A1','orthography','¿Qué palabra está bien escrita?','["gente", "jente", "guente", "xente"]'::jsonb,'gente',4,true,'mcq','es'),
('A2','grammar','Ayer nosotros ___ una película muy buena.','["vimos", "vemos", "veremos", "veíamos"]'::jsonb,'vimos',1,true,'mcq','es'),
('A2','grammar','Cuando era niño, ___ mucho al fútbol.','["jugaba", "jugué", "jugaré", "juegue"]'::jsonb,'jugaba',2,true,'mcq','es'),
('A2','grammar','Si tengo tiempo, ___ contigo.','["iré", "iría", "fuera", "iba"]'::jsonb,'iré',3,true,'mcq','es'),
('A2','grammar','Es importante que tú ___ temprano.','["llegues", "llegas", "llegarás", "llegabas"]'::jsonb,'llegues',4,true,'mcq','es'),
('A2','grammar','Ella es ___ alta que su hermano.','["más", "muy", "tan", "mucho"]'::jsonb,'más',5,true,'mcq','es'),
('A2','grammar','Ya ___ terminado el informe.','["he", "has ya", "había de", "hube de"]'::jsonb,'he',6,true,'mcq','es'),
('A2','grammar','Le di el libro ___ María.','["a", "en", "de", "por"]'::jsonb,'a',7,true,'mcq','es'),
('A2','grammar','Estoy buscando un piso que ___ barato.','["sea", "es", "era", "fue"]'::jsonb,'sea',8,true,'mcq','es'),
('A2','grammar','Se lo dije, pero no me ___ caso.','["hizo", "hace", "hará", "haría"]'::jsonb,'hizo',9,true,'mcq','es'),
('A2','grammar','Llevo dos años ___ español.','["estudiando", "estudiar", "estudiado", "estudio"]'::jsonb,'estudiando',10,true,'mcq','es'),
('A2','vocabulary','Una persona que cura a los enfermos es un:','["médico", "abogado", "ingeniero", "cocinero"]'::jsonb,'médico',1,true,'mcq','es'),
('A2','vocabulary','El contrario de « barato » es:','["caro", "corto", "lento", "limpio"]'::jsonb,'caro',2,true,'mcq','es'),
('A2','vocabulary','Cuando hace mucho frío, nos ponemos un:','["abrigo", "biquini", "sombrero de paja", "ventilador"]'::jsonb,'abrigo',3,true,'mcq','es'),
('A2','vocabulary','¿Qué significa « estar harto de algo » ?','["Estar cansado de algo", "Tener mucha hambre", "Estar contento", "Tener prisa"]'::jsonb,'Estar cansado de algo',4,true,'mcq','es'),
('A2','vocabulary','En el aeropuerto facturamos el:','["equipaje", "alquiler", "recibo", "cambio"]'::jsonb,'equipaje',5,true,'mcq','es'),
('A2','vocabulary','Un sinónimo de « rápidamente » es:','["deprisa", "despacio", "apenas", "acaso"]'::jsonb,'deprisa',6,true,'mcq','es'),
('A2','vocabulary','La persona que atiende en un restaurante es el:','["camarero", "cartero", "peluquero", "bombero"]'::jsonb,'camarero',7,true,'mcq','es'),
('A2','vocabulary','¿Qué significa « echar una mano » ?','["Ayudar", "Despedirse", "Enfadarse", "Marcharse"]'::jsonb,'Ayudar',8,true,'mcq','es'),
('A2','reading','Lea: « El museo abre todos los días salvo los lunes. La entrada es gratuita para menores de doce años. » ¿Quién no paga?','["Los menores de doce años", "Los estudiantes", "Los jubilados", "Nadie"]'::jsonb,'Los menores de doce años',1,true,'mcq','es'),
('A2','reading','Lea: « Aunque llovía, decidimos salir a caminar por la playa. » ¿Qué tiempo hacía?','["Llovía", "Nevaba", "Hacía sol", "Había niebla"]'::jsonb,'Llovía',2,true,'mcq','es'),
('A2','reading','Lea: « Se busca camarero con experiencia. Horario de tarde. Enviar currículum al correo del bar. » ¿Qué piden al candidato?','["Enviar su currículum", "Llamar por teléfono", "Presentarse por la mañana", "Traer referencias en papel"]'::jsonb,'Enviar su currículum',3,true,'mcq','es'),
('A2','reading','Lea: « Marta ha aprobado el examen después de estudiar tres meses. » ¿Cuál es el resultado?','["Aprobó el examen", "Suspendió el examen", "No se presentó", "Aplazó el examen"]'::jsonb,'Aprobó el examen',4,true,'mcq','es'),
('A2','orthography','¿Qué frase está bien escrita?','["Había mucha gente en la plaza.", "Avía mucha gente en la plaza.", "Habían mucha gente en la plaza.", "Abía mucha gente en la plaza."]'::jsonb,'Había mucha gente en la plaza.',1,true,'mcq','es'),
('A2','orthography','¿Qué palabra está bien escrita?','["excursión", "escursión", "exkursión", "excurción"]'::jsonb,'excursión',2,true,'mcq','es'),
('A2','orthography','¿Qué palabra está bien escrita?','["reunión", "reunnión", "reuñion", "rreunión"]'::jsonb,'reunión',3,true,'mcq','es'),
('A2','orthography','¿Qué opción es correcta?','["Voy a ver si viene.", "Voy a haber si viene.", "Boy a ver si viene.", "Voy aver si viene."]'::jsonb,'Voy a ver si viene.',4,true,'mcq','es');